### ISSUE TITLE
Please update npm repository

### ISSUE THREAD

**Issue by atnartur** [thisispete/docpad-plugin-swig#7]
You updated package.json file and setted version to 2.0.3. But [in npm there is only 0.0.3 version](https://www.npmjs.com/package/docpad-plugin-swig). And in my case I cannot install plugin with `docpad install swig`:

```
info: Welcome to DocPad v6.78.4 
notice: Please donate to DocPad or have your company sponsor it: http://docpad.org/donate
info: Contribute: http://docpad.org/docs/contribute
info: Plugins: eco
info: Environment: development
npm WARN package.json no-skeleton.docpad@0.1.0 No repository field.
npm WARN package.json no-skeleton.docpad@0.1.0 No license field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "...\\node.exe" "...\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "docpad-plugin-swig@2" "--save"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: docpad-plugin-swig@'>=2.0.0 <3.0.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.0.1","0.0.2","0.0.3"]
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'no-skeleton.docpad'
npm ERR! notarget

npm ERR! Please include the following file with any support request:
npm ERR!     ...\npm-debug.log
error: The action completed successfully
error: An error occured:

Error: Command exited with a non-zero status code.
  at Object.safeps.prepareExecutableResult (...\node_modules\docpad\node_modules\safeps\out\lib\safeps.js:190:24)
  at ChildProcess.<anonymous> (...\node_modules\docpad\node_modules\safeps\out\lib\safeps.js:322:29)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:172:7)
  at maybeClose (internal/child_process.js:821:16)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

To report the above, follow the guide at: http://docpad.org/bug-report
Error: Command exited with a non-zero status code.
  at Object.safeps.prepareExecutableResult (...\node_modules\docpad\node_modules\safeps\out\lib\safeps.js:190:24)
  at ChildProcess.<anonymous> (...\node_modules\docpad\node_modules\safeps\out\lib\safeps.js:322:29)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:172:7)
  at maybeClose (internal/child_process.js:821:16)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

**Comment by thisispete** [comment]
2.0.3 is pushed, sorry about that, this project is no longer maintained, > 3 years old.

**Comment by atnartur** [comment]
But docpad don`t have another swig plugin. Thanks!
